#!/usr/bin/env -S uv run --script

# SPDX-FileCopyrightText: COMPLY contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///

"""Generate Rust source file with SPDX License List and Exception IDs.

Fetches https://spdx.org/licenses/licenses.json and produces
src/spdx_list.rs containing all known license and exception IDs.
"""

import json
import sys
from pathlib import Path
from urllib.request import urlopen

SPDX_URL = "https://spdx.org/licenses/licenses.json"
OUTPUT = Path(__file__).resolve().parent.parent / "crates" / "comply" / "src" / "spdx_list.rs"

HEADER = """\
// SPDX-FileCopyrightText: 2026 COMPLY contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

// !!! AUTO-GENERATED by scripts/generate-spdx.py !!!
// Source: SPDX License List {version}
// Do not edit by hand -- re-run the generator script to update.

/// SPDX license identifiers known to this version of the SPDX License List.
#[rustfmt::skip]
pub(crate) const KNOWN_LICENSES: &[&str] = &[
{licenses}
];

/// SPDX exception identifiers known to this version of the SPDX License List.
#[rustfmt::skip]
pub(crate) const KNOWN_EXCEPTIONS: &[&str] = &[
{exceptions}
];

/// Identifiers the SPDX License List marks as deprecated. These are still
/// "known" -- they appear in `KNOWN_LICENSES` -- but a project using one should
/// migrate to its replacement, so REUSE reports them separately.
#[rustfmt::skip]
pub(crate) const DEPRECATED_LICENSES: &[&str] = &[
{deprecated}
];
"""


def fetch_json(url: str) -> dict:
    with urlopen(url, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))


def main() -> int:
    print(f"Fetching {SPDX_URL}...")
    data = fetch_json(SPDX_URL)
    version = data.get("licenseListVersion", "unknown")
    licenses = data.get("licenses", [])

    known_ids: list[str] = []
    exception_ids: list[str] = []
    deprecated_ids: list[str] = []

    for lic in licenses:
        lid = lic["licenseId"]
        if lid.startswith("LicenseRef-"):
            continue
        if lic.get("isDeprecatedLicenseId", False):
            known_ids.append(lid)
            deprecated_ids.append(lid)
        elif lic.get("isFsfLibre", False) or lic.get("isOsiApproved", False):
            known_ids.append(lid)
        else:
            known_ids.append(lid)

    known_ids.sort()

    # Exceptions are also in this same list, but we handle them separately.
    # SPDX keeps exceptions in the same JSON; we look for the specific exception
    # file entries that have "exception" in their ID pattern or are listed
    # as SPDX exceptions.
    EXCEPTION_IDS = {
        "389-exception",
        "Autoconf-exception-2.0",
        "Autoconf-exception-3.0",
        "Bison-exception-2.24",
        "Bootloader-exception",
        "CLISP-exception-2.0",
        "Classpath-exception-2.0",
        "DigiRule-FOSS-exception",
        "eCos-exception-2.0",
        "Fawkes-Runtime-exception",
        "FLTK-exception",
        "Font-exception-2.0",
        "freertos-exception-2.0",
        "GCC-exception-2.0",
        "GCC-exception-3.1",
        "GNJOM-exception",
        "LZMA-exception",
        "LLVM-exception",
        "Linux-syscall-note",
        "mif-exception",
        "Nokia-Qt-exception-1.1",
        "OCaml-LGPL-linking-exception",
        "OCCT-exception-1.0",
        "OpenJDK-assembly-exception-1.0",
        "openvpn-openssl-exception",
        "PS-or-PDF-font-exception-20170817",
        "Qt-GPL-exception-1.0",
        "Qt-LGPL-exception-1.1",
        "Qwt-exception-1.0",
        "SSLeay-standalone-exception",
        "Swift-exception",
        "Universal-FOSS-exception-1.0",
        "vsftpd-openssl-exception",
        "WxWindows-exception-3.1",
    }

    # Separate known license IDs from exception IDs
    final_known = [lid for lid in known_ids if lid not in EXCEPTION_IDS]
    final_exceptions = sorted(EXCEPTION_IDS)

    # Format as Rust array
    final_deprecated = sorted(set(deprecated_ids) - EXCEPTION_IDS)

    # Trailing comma on every entry, including the last: rustfmt wants one, and
    # without it `mise run fmt:check` fails on a freshly generated file.
    ids_formatted = "\n".join(f'    "{lid}",' for lid in final_known)
    exc_formatted = "\n".join(f'    "{eid}",' for eid in final_exceptions)
    dep_formatted = "\n".join(f'    "{lid}",' for lid in final_deprecated)

    content = HEADER.format(
        version=version,
        licenses=ids_formatted,
        exceptions=exc_formatted,
        deprecated=dep_formatted,
    ).rstrip() + "\n"

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    count_lic = len(final_known)
    count_exc = len(final_exceptions)
    print(f"Writing {OUTPUT} (SPDX {version}, {count_lic} licenses, {count_exc} exceptions)...")
    OUTPUT.write_text(content)

    return 0


if __name__ == "__main__":
    sys.exit(main())
